[package]
name = "bring-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
reqwest = { version = "0.12.8", features = ["json"] }
serde = { version = "1.0.213", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
